### ISSUE TITLE
Aplicación desplegada

### ISSUE THREAD

**Issue by labra** [Arquisoft/dechat_es2a#19]
Estoy creando una página web en la que voy a recolectar todas las aplicaciones desplegadas para compartir el enlace con Inrupt.

En vuestro caso, la aplicación final desplegada debería estar en: [https://arquisoft.github.io/dechat_es2a/](https://arquisoft.github.io/dechat_es2a/), sin embargo, en ese enlace ahora mismo está la documentación técnica.

La documentación técnica debería estar en [https://arquisoft.github.io/dechat_es2a/docs](https://arquisoft.github.io/dechat_es2a/docs).

Cuando corrigáis esos enlaces y tengáis la aplicación y la documentación desplegadas, enviadme un correo para cerrar este issue y añadir vuestra aplicación a la lista.

**Comment by RaulGarciaArenas** [comment]
Ya hemos desplegado la aplicación. Puedes cerrar este issue.

**Comment by labra** [comment]
Añadido enlace a la Web.
